# 项目相关配置
ledger:
  # 名称
  name: ledger
  # 版本
  version: 3.9.0
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ledger/uploadPath，Linux配置 /home/ledger/uploadPath）
  profile: /Users/leixingbang
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证
  captchaType: math

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ledger: info
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 10

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: 12345678
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 2400

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.ledger.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping:

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
oauth2:
  #client_id: publicCode
  #client_secret: baf561059dc04eada61533af95c8d298
  client_id: ryjManage
  client_secret: a892c5eef4e24ece8646975f6d7389a4
  accesstoken_uri: https://work.ctg.com.cn/idp/oauth2/getToken?client_id=%s&grant_type=%s&code=%s&client_secret=%s
  authorize_uri: https://work.ctg.com.cn/idp/oauth2/authorize?redirect_uri=${oauth2.redirect_uri}&state=abs&client_id=${oauth2.client_id}&response_type=code
  #authorize_uri: http://www.baidu.com
  revokeToken_uri: https://work.ctg.com.cn/idp/oauth2/revokeToken?access_token=%s
  userinfo_uri: https://work.ctg.com.cn/idp/oauth2/getUserInfo?access_token=%s&client_id=%s&uid=%s
  #redirect_uri: http://zpd8jg4m.c87e2267-1001-4c70-bb2a-ab41f3b81aa3.dcloud.ctg.com.cn/code
  #redirect_uri: http://10.188.241.80/prod-api/oauth2sso/code
  redirect_uri: http://127.0.0.1:6060/oauth2sso/code
url:
    oauth2SsoUrl: http://127.0.0.1:1024/oauth2SsoLogin
    mySystemHomeUrl: http://127.0.0.1:1024/index